### ISSUE TITLE
Figure out how to test code that uses PreferencesFetcher (eg. wakeup feature)

### ISSUE THREAD

**Issue by RauschRobin** [RauschRobin/AdvancedSoftwareEngineering#12]
Currently you cannot test the wakeup feature class because the constructor of wakeup uses preferencesfetcher and the file preferences.yaml cannot be found via tests.

**Comment by TobiasGleiter** [comment]
Funktioniert wenn man in der workflow file ein working-directory auf src setzt. Alle test müssen daher in src sein, was ja kein Problem ist.
