### ISSUE TITLE
Carschtens tells me where to go eat every minute. Seems like spam and is annoying

### ISSUE THREAD

**Issue by RauschRobin** [RauschRobin/AdvancedSoftwareEngineering#51]
Can you fix this so that Carschten only tells me this once per meal?

**Comment by TobiasGleiter** [comment]
After the merge with fix-erneahrungsplaner it should be fixed

**Comment by RauschRobin** [comment]
@TobiasGleiter Please link the issue with the branch/pull request where you'll fix it. On the right you can see development. Just click on that and choose the correct repo and branch or pull request.
